### ISSUE TITLE
Windows binaries x64 (no BMI2) executable are missing

### ISSUE THREAD

**Issue by yellow-panther** [maksimKorzh/Chenglite#1]
Can you build an executable file for Windows and host it on GitHub, too? Unfortunately I am not a programmer , but your software is mentioned here: http://talkchess.com/forum3/viewtopic.php?f=2&t=68418

BMI2 = https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets

**Comment by maksimKorzh** [comment]
I'll provide windows version in future, maybe in a month, for now a lot of bugs in search are arising, so it needs time to be fixed. Sorry for that. You can leave your e-mail and I'll write you as soon as the windows version is going to be complete. The link you've mentioned is more like a place where chess engine developers are exchanging their experience. Both of releases are not production ready, I'll point that out in the release section. Thanks for your interest.

**Comment by yellow-panther** [comment]
Tony Mokonen´s compile for Windows 64-bit is here: http://tonyschess.x10host.com/Chenglite11TM.rar 
Do you know CCWiki http://computer-chess.org/doku.php?id=home - http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:index  ? Most chess engines are able to run with the mode e.g. 40 moves /4 minutes or 40 minutes cf. http://computerchess.org.uk/ccrl/4040/index.html or http://www.cegt.net/
