### ISSUE TITLE
Chenglite 1.0 for Mac OS  by Dariusz etc.

### ISSUE THREAD

**Issue by yellow-panther** [maksimKorzh/Chenglite#2]
Hello Maksim,

are your data  identical with this person http://ratings.fide.com/card.phtml?event=34105360 ?

http://talkchess.com/forum3/viewtopic.php?f=2&t=68418 for Windows / Mac OS builds

**Comment by maksimKorzh** [comment]
#yellow-panther , I've made the windows version, see releases and also asked to recompile source for MAC, see the forum link you've sent me.
